@startuml
object 社員1 {
  氏名 = "高橋洋平"
}

object 社員2 {
  氏名 = "樋口正之"
}

object 資格1 {
  資格の名称 = "情報処理安全確保支援士"
}

object 資格2 {
  資格の名称 = "LinuC試験Level1"
}

社員1 --o 資格1
社員1 --o 資格2
社員2 --o 資格1

@enduml
