@startuml
[*] --right-->価格待機中 :電源ON
state 価格待機中{
}
state スイッチ選択待機中{
}
state 商品提供中{
}
価格待機中  -down-> スイッチ選択待機中 :価格を投入する
スイッチ選択待機中 -right-> 商品提供中 :スイッチを押す
商品提供中 -up-> 価格待機中 :商品を提供する
価格待機中 --right--> [*] :電源OFF
@enduml
