@startuml 7-1
|ホテル宿泊システム|
|ユーザ|

|ユーザ|
start
:ユーザ名を入力する;
:パスワードを入力する;
|ホテル宿泊システム|
while (ユーザ名とパスワードのペアは適切か？)
|ユーザ|
:ユーザ名を再度入力する;
:パスワードを再度入力する;
endwhile
|ホテル宿泊システム|
:予約する;
stop
@enduml