@startuml
left to right direction
actor 社員
actor 人事担当者
rectangle 新規従業員登録システム{
usecase 社員の情報を従業員システムに登録する
usecase 社員情報を参照する
usecase 社員情報を変更する
usecase 変更届を提出する as input
usecase 社員情報を編集する
}
人事担当者 --|> 社員
社員 --> 社員情報を参照する
社員 --> 社員情報を変更する
input .> 社員情報を編集する : <<extend>>
社員情報を変更する .> input : <<include>>
人事担当者 --> 社員の情報を従業員システムに登録する
人事担当者 --> 社員情報を編集する
@enduml