@startuml 演習4-1
hide footbox
actor 客 as customer
participant ":フロア定員" as clerk
participant ":料理人" as cooker
activate customer
customer -> clerk:ラーメンを注文する
activate clerk
clerk -> cooker:調理を指示する
activate cooker
cooker -> cooker:料理をする
clerk <-- cooker:ラーメン
deactivate cooker
deactivate clerk
customer <<-- clerk:ラーメン
deactivate customer
@enduml