@startuml
left to right direction
actor 社員
actor 人事担当者
rectangle 新規従業員登録システム{
usecase 社員情報を登録する
usecase 社員情報を参照する
usecase (<u>社員情報を編集する</u>\n拡張点\n変更届が提出されたら) as edit
}
人事担当者 --|> 社員
社員 --> 社員情報を参照する
人事担当者 --> 社員情報を登録する
社員情報を登録する .> edit : <<extend>>
人事担当者 --> edit
@enduml