@startuml
object 顧客1 {
  氏名 = "高橋洋平"
}

object 顧客2 {
  氏名 = "高田利恵"
}

object テレビ {
  型式 = "V12345"
}

object 冷蔵庫 {
  型式 = "R8765"
}

object 注文1 {
  注文日 = "11月21日"
  数量 = 2
}

object 注文2 {
  注文日 = "12月23日"
  数量 = 1
}

顧客1 --- 注文1
顧客2 --- 注文2

テレビ --- 注文1
冷蔵庫 --- 注文1
冷蔵庫 --- 注文2

@enduml