@startuml ライントレーサー
電源SW_OFF --> 電源SW_ON : スイッチを入れる
電源SW_ON --> 電源SW_OFF : スイッチを切る
state 電源SW_ON {
    右旋回 : 右モータOFF, 左モータON
    左旋回 : 右モータON, 左モータOFF
    右旋回 --> 左旋回 : ラインを外れる
    左旋回 --> 右旋回 : ラインに乗る
}
@enduml