@startuml
left to right direction
class ディスペンサー{
}
class スイッチ{
}
class 価格システム{
}
class ディストリビューター装置{
}
ディスペンサー "1"*----"*"スイッチ 
ディスペンサー "1"*----"1"価格システム
ディスペンサー "1"*----"1"ディストリビューター装置
@enduml
