@startuml 予定管理
[*] --right--> メイン
state メイン{
}
state 予定と確認{
}
state ユーザーのターン{
}
state 現在のターン{
}
メイン -down-> 予定と確認 : 予定と確認へ遷移
予定と確認 -up-> メイン : 取り消しする
予定と確認 -right-> ユーザーのターン : 登録ボタンを押す
予定と確認 -right-> ユーザーのターン : 確認ボタンを押す
ユーザーのターン -up-> メイン : メインへ遷移
メイン -down-> 現在のターン : 現在のターンへ遷移
現在のターン -up-> メイン : メインへ遷移
メイン --right--> [*]
@enduml
